# -*- coding: utf-8 -*-
"""Tugas Besar Deep Learning CNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WagHDdnbm8RSDzL5U7NkoQE16N4uLRau
"""

from google.colab import drive
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

# 1. Sambungkan ke Drive
drive.mount('/content/drive')

import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import load_img, img_to_array # Added missing imports

# --- PENGATURAN (Sesuaikan path ini dengan Drive-mu) ---
input_folder_path = '/content/drive/MyDrive/Deeplearning'  # GANTI INI
output_folder_path = '/content/drive/MyDrive/Dataset_Siap_Training' # Folder baru buat hasil

# Target jumlah gambar per kelas (misal jadi 50 gambar per ekspresi)
target_jumlah = 50
# -------------------------------------------------------

datagen = ImageDataGenerator(
    rotation_range=20,      # Putar gambar
    width_shift_range=0.2,  # Geser kiri-kanan
    height_shift_range=0.2, # Geser atas-bawah
    shear_range=0.2,        # Miringkan
    zoom_range=0.2,         # Zoom in/out
    horizontal_flip=True,   # Balik horizontal
    fill_mode='nearest'
)

classes = ['Bingung', 'Lelah', 'Mengerti']

for kelas in classes:
    # Buat folder output
    save_dir = os.path.join(output_folder_path, kelas)
    os.makedirs(save_dir, exist_ok=True)

    # Ambil list foto asli
    source_dir = os.path.join(input_folder_path, kelas)

    # Added check for directory existence
    if not os.path.exists(source_dir):
        print(f"Error: Folder '{source_dir}' tidak ditemukan. Mohon periksa path 'input_folder_path' Anda di Google Drive.")
        continue # Skip to the next class if directory not found

    file_names = os.listdir(source_dir)

    print(f"Sedang memproses kelas: {kelas} ({len(file_names)} gambar asli)...")

    # Mulai Augmentasi
    count = 0
    for file_name in file_names:
        img_path = os.path.join(source_dir, file_name)

        # Cek apakah file gambar valid
        if not file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            continue

        # Load gambar
        img = load_img(img_path)
        x = img_to_array(img)
        x = x.reshape((1,) + x.shape)

        # Generate variasi baru
        i = 0
        for batch in datagen.flow(x, batch_size=1, save_to_dir=save_dir, save_prefix='aug', save_format='jpg'):
            i += 1
            count += 1
            if i >= 5: # Dari 1 foto bikin 5 variasi
                break

    print(f"Selesai! Total gambar '{kelas}' sekarang ada di folder output.")

# --- KODE 2: TRAINING CNN ---
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# 1. Siapkan Data Generator (Ambil dari folder hasil augmentasi tadi)
TRAIN_DIR = '/content/drive/MyDrive/Dataset_Siap_Training'
IMG_SIZE = (224, 224) # Ukuran standar MobileNet
BATCH_SIZE = 16

# Define the classes explicitly (from the previous cell's 'classes' variable)
# This is crucial to match the model's output layer
TARGET_CLASSES = ['Bingung', 'Lelah', 'Mengerti']

train_datagen = ImageDataGenerator(
    rescale=1./255,       # Normalisasi piksel
    validation_split=0.2  # 20% buat ujian (validasi)
)

print("Menyiapkan data Training...")
train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',
    classes=TARGET_CLASSES # Specify the target classes
)

print("Menyiapkan data Validasi...")
val_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',
    classes=TARGET_CLASSES # Specify the target classes
)

# 2. Bangun Model (Transfer Learning)
# Ambil otak MobileNet tapi buang bagian kepalanya (include_top=False)
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Bekukan base_model biar ilmunya gak hilang
base_model.trainable = False

# Tambahkan kepala baru sesuai kasus kita (3 Kelas)
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.2)(x) # Biar gak overfitting
predictions = Dense(len(TARGET_CLASSES), activation='softmax')(x) # Use len(TARGET_CLASSES) for robustness

model = Model(inputs=base_model.input, outputs=predictions)

# 3. Compile Model
model.compile(optimizer=Adam(learning_rate=0.0001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 4. Mulai Training
print("\nMulai Training CNN... (Sabar ya)")
history = model.fit(
    train_generator,
    epochs=20,  # Coba 20 putaran dulu
    validation_data=val_generator
)

# 5. Simpan Model
model.save('model_cnn_tubes.h5')
print("\nSelesai! Model disimpan sebagai 'model_cnn_tubes.h5'")

from google.colab import files
files.download('/content/model_cnn_tubes.h5')
from google.colab import drive
drive.mount('/content/drive')
import shutil

# Mengcopy model.h5 ke Folder utama Google Drive Anda
shutil.copy('model_cnn_tubes.h5', '/content/drive/MyDrive/model_tugas_besar.h5')

print("Berhasil! Cek Google Drive Anda, cari file bernama 'model_tugas_besar.h5'")

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(1, len(acc) + 1)

plt.figure(figsize=(12, 5))

# Grafik Akurasi
plt.subplot(1, 2, 1)
plt.plot(epochs, acc, 'b', label='Training Acc')
plt.plot(epochs, val_acc, 'r', label='Validation Acc')
plt.title('Akurasi Training vs Validasi')
plt.legend()

# Grafik Loss
plt.subplot(1, 2, 2)
plt.plot(epochs, loss, 'b', label='Training Loss')
plt.plot(epochs, val_loss, 'r', label='Validation Loss')
plt.title('Loss Training vs Validasi')
plt.legend()

plt.show()



from tensorflow.keras.models import load_model
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Muat model yang telah disimpan dari Google Drive
model = load_model('/content/drive/MyDrive/model_tugas_besar.h5')

# --- Re-initialize val_generator ---
TRAIN_DIR = '/content/drive/MyDrive/Dataset_Siap_Training'
IMG_SIZE = (224, 224) # Ukuran standar MobileNet
BATCH_SIZE = 16
TARGET_CLASSES = ['Bingung', 'Lelah', 'Mengerti'] # Define target classes again

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

print("Menyiapkan data Validasi untuk evaluasi...")
val_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',
    classes=TARGET_CLASSES
)
# --- End of re-initialization ---

# Evaluasi model pada data validasi
loss_test, accuracy_test = model.evaluate(val_generator)

print(f"\nHasil Evaluasi Model:")
print(f"Loss pada data validasi: {loss_test:.4f}")
print(f"Akurasi pada data validasi: {accuracy_test:.4f}")

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Memuat model yang telah disimpan (jika belum dimuat)
# model = load_model('model_cnn_tubes.h5')
# Baris ini di-comment karena model sudah dimuat sebelumnya di cell 658b8802

# Dapatkan prediksi pada data validasi
val_generator.reset() # Penting untuk mereset generator sebelum mendapatkan prediksi
predictions = model.predict(val_generator)
y_pred = np.argmax(predictions, axis=1)

# Dapatkan label sebenarnya dari generator validasi
y_true = val_generator.classes

# Pastikan urutan kelas sesuai dengan yang digunakan oleh generator
# val_generator.class_indices akan memberi tahu kita pemetaan indeks ke nama kelas
class_labels = list(val_generator.class_indices.keys())

print("\n--- Classification Report ---")
print(classification_report(y_true, y_pred, target_names=class_labels))

print("\n--- Confusion Matrix ---")
cm = confusion_matrix(y_true, y_pred)
print(cm)

# Visualisasi Confusion Matrix
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Menampilkan ringkasan arsitektur model (Layer, Output Shape, Param #)
model.summary()